TARGET_LABEL="dev.to"
CSL_FILE="ieee.csl"
REFERENCES_HEADING="References"
REFERENCES_NUMBERED="1"
OUTPUT_EXT="md"

EXTRA_LUA_FILTER="$SCRIPT_DIR/devto-math.lua"

FRONT_MATTER_TEMPLATE='---
title: "{{TITLE}}"
published: false
description: ""
tags: {{TAGS}}
---
'
FRONT_MATTER_COMMENTED="0"

INCLUDE_H1_TITLE="0"
INCLUDE_BYLINE="0"