TARGET_LABEL="Journal"
CSL_FILE="chicago-author-date.csl"
REFERENCES_HEADING="Bibliography"
REFERENCES_NUMBERED="0"
OUTPUT_EXT="md"

FRONT_MATTER_TEMPLATE=""
FRONT_MATTER_COMMENTED="0"

INCLUDE_H1_TITLE="1"
INCLUDE_BYLINE="1"
