TARGET_LABEL="medium.com"
CSL_FILE="ieee.csl"
REFERENCES_HEADING="References"
REFERENCES_NUMBERED="1"
OUTPUT_EXT="md"

FRONT_MATTER_TEMPLATE=""
FRONT_MATTER_COMMENTED="0"

INCLUDE_H1_TITLE="1"
INCLUDE_BYLINE="1"
