TARGET_LABEL="medium.com"
CSL_FILE="ieee.csl"
REFERENCES_HEADING="References"
REFERENCES_NUMBERED="1"
OUTPUT_EXT="html"

EXTRA_LUA_FILTER="$SCRIPT_DIR/plain-math.lua"

FRONT_MATTER_TEMPLATE=""
FRONT_MATTER_COMMENTED="0"

INCLUDE_H1_TITLE="1"
INCLUDE_BYLINE="0"